/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.HoaDon;
import Model.ThanhToan;
import Service.HoaDonDAL;
import Service.ThanhToanDAL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class HoaDonnJPane extends javax.swing.JPanel {

    private DefaultTableModel tableModel;
    public static HoaDonnJPane instance;

    /**
     * Creates new form HoaDonnJPane
     */
    public HoaDonnJPane() {
        initComponents();
        instance = this;
        initTable();
        loadData();
    }

    public void initTable() {
        tableModel = new DefaultTableModel();
        String[] cols = new String[]{"Mã HĐ", "SĐT", "SP Đã Mua", "SL", "Thời Gian", "PT Thanh Toán", "Tổng Tiền", "Tiền Nhận", "Tiền Thừa", "Mã NV"};
        tableModel.setColumnIdentifiers(cols);
        tblHoaDon.setModel(tableModel);
    }

    public void loadData() {
        List<HoaDon> hoaDonList = HoaDonDAL.getAllHoaDon();
        if (hoaDonList.isEmpty()) {
            System.out.println("Không có dữ liệu hóa đơn!");
            return;
        }
        tableModel.setRowCount(0);
        for (HoaDon hd : hoaDonList) {
//            String spDaMua = hd.getSpDaMua();
//            int slTong = tinhTongSL(spDaMua);
            
            tableModel.addRow(new Object[]{
                hd.getMaHD(), 
                //hd.getMaKH(), 
                hd.getSdtKH(), 
                hd.getSpDaMua(),
                hd.getSoLuong(),
                hd.getThoiGianMua(), 
                //hd.getMaSP(),
                hd.getPhuongThucTT(), 
                hd.getTongTienTT(), 
                hd.getTienDaNhan(), 
                hd.getTienThua(), 
                hd.getMaNV()
            });
        }
    }
    
    private int tinhTongSL(String spDaMua) {
        if (spDaMua == null || spDaMua.trim().isEmpty()) {
            return 0;
        }
        int cumSL = 0;
        String[] cumSP = spDaMua.split(",");
        for (String sp : cumSP) {
            sp = sp.trim();
            String[] parts = sp.split("\\s", 2);
            try {
                int sl = Integer.parseInt(parts[0]);
                cumSL = cumSL + sl;
            } catch (Exception e) {
            }
        }
        return cumSL;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboTimKiem = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        cboTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SĐT Khách Hàng", "Thời Gian" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tìm kiếm");

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblHoaDon);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 153));
        jLabel19.setText("THÔNG TIN HÓA ĐƠN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLamMoi)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(cboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnTimKiem))))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem)
                    .addComponent(cboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLamMoi)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:                                                                               
        String luaChon = (String) cboTimKiem.getSelectedItem();
        String tuKhoa = txtTimKiem.getText().trim();
        
        if (tuKhoa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập từ khóa cần tìm kiếm!");
            return;
        }
        
        List<ThanhToan> danhSachHoaDon = new ArrayList<>();
        try {
            /*if (luaChon.equals("Mã hóa đơn")) {
                if (!tuKhoa.matches("\\d+")) {
                    JOptionPane.showMessageDialog(this, "Mã hóa đơn phải nhập số nguyên dương!");
                    return;
                }
                danhSachHoaDon = HoaDonDAL.findMaHD(Integer.parseInt(tuKhoa));
            } else*/ if (luaChon.equals("SĐT Khách Hàng")) {
//                if (!tuKhoa.matches("\\d+")) {
//                    JOptionPane.showMessageDialog(this, "Số điện thoại phải là số nguyên!");
//                    return;
//                }
                danhSachHoaDon = HoaDonDAL.findSDT(tuKhoa);
            } else if (luaChon.equals("Thời Gian")) {
                danhSachHoaDon = HoaDonDAL.findThoiGian(tuKhoa);
            }
            hienThiKetQuaTimKiem(danhSachHoaDon);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã hóa đơn phải nhập số nguyên dương!");
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm hóa đơn!");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        loadData();
        txtTimKiem.setText("");
        cboTimKiem.setSelectedIndex(0);
    }//GEN-LAST:event_btnLamMoiActionPerformed
    private void hienThiKetQuaTimKiem(List<ThanhToan> danhSach) {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0);
        for (ThanhToan tt : danhSach) {
            model.addRow(new Object[]{
                tt.getMaHD(),
                //tt.getMaKH(),
                tt.getSdtKH(),
                tt.getSpDaMua(),
                tt.getSoLuong(),
                tt.getThoiGianMua(),
                //tt.getMaSP(),
                tt.getPhuongThucTT(),
                tt.getTongTienTT(),
                tt.getTienDaNhan(),
                tt.getTienThua(),
                tt.getMaNV()});
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cboTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
